version: '3'

services:
  conductor:
    image: conductor:0.0.1
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"