// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.11.2
// source: conduct.proto

package conductor

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResourceRequest_ResourceType int32

const (
	ResourceRequest_METATRADER_4 ResourceRequest_ResourceType = 0
	ResourceRequest_METATRADER_5 ResourceRequest_ResourceType = 1
)

// Enum value maps for ResourceRequest_ResourceType.
var (
	ResourceRequest_ResourceType_name = map[int32]string{
		0: "METATRADER_4",
		1: "METATRADER_5",
	}
	ResourceRequest_ResourceType_value = map[string]int32{
		"METATRADER_4": 0,
		"METATRADER_5": 1,
	}
)

func (x ResourceRequest_ResourceType) Enum() *ResourceRequest_ResourceType {
	p := new(ResourceRequest_ResourceType)
	*p = x
	return p
}

func (x ResourceRequest_ResourceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResourceRequest_ResourceType) Descriptor() protoreflect.EnumDescriptor {
	return file_conduct_proto_enumTypes[0].Descriptor()
}

func (ResourceRequest_ResourceType) Type() protoreflect.EnumType {
	return &file_conduct_proto_enumTypes[0]
}

func (x ResourceRequest_ResourceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResourceRequest_ResourceType.Descriptor instead.
func (ResourceRequest_ResourceType) EnumDescriptor() ([]byte, []int) {
	return file_conduct_proto_rawDescGZIP(), []int{0, 0}
}

type ResourceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResourceType ResourceRequest_ResourceType `protobuf:"varint,1,opt,name=resource_type,json=resourceType,proto3,enum=conductor.ResourceRequest_ResourceType" json:"resource_type,omitempty"`
	Params       map[string]string            `protobuf:"bytes,5,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *ResourceRequest) Reset() {
	*x = ResourceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_conduct_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceRequest) ProtoMessage() {}

func (x *ResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conduct_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceRequest.ProtoReflect.Descriptor instead.
func (*ResourceRequest) Descriptor() ([]byte, []int) {
	return file_conduct_proto_rawDescGZIP(), []int{0}
}

func (x *ResourceRequest) GetResourceType() ResourceRequest_ResourceType {
	if x != nil {
		return x.ResourceType
	}
	return ResourceRequest_METATRADER_4
}

func (x *ResourceRequest) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

type AttachResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error    string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	RpcQueue string `protobuf:"bytes,5,opt,name=rpc_queue,json=rpcQueue,proto3" json:"rpc_queue,omitempty"`
	Exchange string `protobuf:"bytes,10,opt,name=exchange,proto3" json:"exchange,omitempty"`
}

func (x *AttachResponse) Reset() {
	*x = AttachResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_conduct_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AttachResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachResponse) ProtoMessage() {}

func (x *AttachResponse) ProtoReflect() protoreflect.Message {
	mi := &file_conduct_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachResponse.ProtoReflect.Descriptor instead.
func (*AttachResponse) Descriptor() ([]byte, []int) {
	return file_conduct_proto_rawDescGZIP(), []int{1}
}

func (x *AttachResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *AttachResponse) GetRpcQueue() string {
	if x != nil {
		return x.RpcQueue
	}
	return ""
}

func (x *AttachResponse) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

type DetachResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *DetachResponse) Reset() {
	*x = DetachResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_conduct_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DetachResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetachResponse) ProtoMessage() {}

func (x *DetachResponse) ProtoReflect() protoreflect.Message {
	mi := &file_conduct_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetachResponse.ProtoReflect.Descriptor instead.
func (*DetachResponse) Descriptor() ([]byte, []int) {
	return file_conduct_proto_rawDescGZIP(), []int{2}
}

func (x *DetachResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_conduct_proto protoreflect.FileDescriptor

var file_conduct_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x64, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x09, 0x63, 0x6f, 0x6e, 0x64, 0x75, 0x63, 0x74, 0x6f, 0x72, 0x22, 0x8e, 0x02, 0x0a, 0x0f, 0x52,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x4c,
	0x0a, 0x0d, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x27, 0x2e, 0x63, 0x6f, 0x6e, 0x64, 0x75, 0x63, 0x74, 0x6f,
	0x72, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0c,
	0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x3e, 0x0a, 0x06,
	0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x63,
	0x6f, 0x6e, 0x64, 0x75, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x1a, 0x39, 0x0a, 0x0b,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x32, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x0c, 0x4d, 0x45, 0x54, 0x41, 0x54,
	0x52, 0x41, 0x44, 0x45, 0x52, 0x5f, 0x34, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x4d, 0x45, 0x54,
	0x41, 0x54, 0x52, 0x41, 0x44, 0x45, 0x52, 0x5f, 0x35, 0x10, 0x01, 0x22, 0x5f, 0x0a, 0x0e, 0x41,
	0x74, 0x74, 0x61, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x70, 0x63, 0x5f, 0x71, 0x75, 0x65, 0x75, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x70, 0x63, 0x51, 0x75, 0x65, 0x75, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x65, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x65, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x22, 0x26, 0x0a, 0x0e,
	0x44, 0x65, 0x74, 0x61, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x32, 0x94, 0x01, 0x0a, 0x10, 0x43, 0x6f, 0x6e, 0x64, 0x75, 0x63, 0x74,
	0x6f, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3f, 0x0a, 0x06, 0x41, 0x74, 0x74,
	0x61, 0x63, 0x68, 0x12, 0x1a, 0x2e, 0x63, 0x6f, 0x6e, 0x64, 0x75, 0x63, 0x74, 0x6f, 0x72, 0x2e,
	0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x19, 0x2e, 0x63, 0x6f, 0x6e, 0x64, 0x75, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x41, 0x74, 0x74, 0x61,
	0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3f, 0x0a, 0x06, 0x44, 0x65,
	0x74, 0x61, 0x63, 0x68, 0x12, 0x1a, 0x2e, 0x63, 0x6f, 0x6e, 0x64, 0x75, 0x63, 0x74, 0x6f, 0x72,
	0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x19, 0x2e, 0x63, 0x6f, 0x6e, 0x64, 0x75, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x44, 0x65, 0x74,
	0x61, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0c, 0x5a, 0x0a, 0x2f,
	0x63, 0x6f, 0x6e, 0x64, 0x75, 0x63, 0x74, 0x6f, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_conduct_proto_rawDescOnce sync.Once
	file_conduct_proto_rawDescData = file_conduct_proto_rawDesc
)

func file_conduct_proto_rawDescGZIP() []byte {
	file_conduct_proto_rawDescOnce.Do(func() {
		file_conduct_proto_rawDescData = protoimpl.X.CompressGZIP(file_conduct_proto_rawDescData)
	})
	return file_conduct_proto_rawDescData
}

var file_conduct_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_conduct_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_conduct_proto_goTypes = []interface{}{
	(ResourceRequest_ResourceType)(0), // 0: conductor.ResourceRequest.ResourceType
	(*ResourceRequest)(nil),           // 1: conductor.ResourceRequest
	(*AttachResponse)(nil),            // 2: conductor.AttachResponse
	(*DetachResponse)(nil),            // 3: conductor.DetachResponse
	nil,                               // 4: conductor.ResourceRequest.ParamsEntry
}
var file_conduct_proto_depIdxs = []int32{
	0, // 0: conductor.ResourceRequest.resource_type:type_name -> conductor.ResourceRequest.ResourceType
	4, // 1: conductor.ResourceRequest.params:type_name -> conductor.ResourceRequest.ParamsEntry
	1, // 2: conductor.ConductorService.Attach:input_type -> conductor.ResourceRequest
	1, // 3: conductor.ConductorService.Detach:input_type -> conductor.ResourceRequest
	2, // 4: conductor.ConductorService.Attach:output_type -> conductor.AttachResponse
	3, // 5: conductor.ConductorService.Detach:output_type -> conductor.DetachResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_conduct_proto_init() }
func file_conduct_proto_init() {
	if File_conduct_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_conduct_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_conduct_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AttachResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_conduct_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DetachResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_conduct_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_conduct_proto_goTypes,
		DependencyIndexes: file_conduct_proto_depIdxs,
		EnumInfos:         file_conduct_proto_enumTypes,
		MessageInfos:      file_conduct_proto_msgTypes,
	}.Build()
	File_conduct_proto = out.File
	file_conduct_proto_rawDesc = nil
	file_conduct_proto_goTypes = nil
	file_conduct_proto_depIdxs = nil
}
